### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by bratanon** [hakandilek/play2-crud#50]
I would like to use this project with Play 2.3.x, but it this project maintained at all now?

How to get the lastest version in my build.sbt?

**Comment by hakandilek** [comment]
Hi @bratanon, latest snapshot build is compatible with play 2.3. You can link to the repository like in the [sample project](https://github.com/hakandilek/play2-crud/blob/master/samples/play2-crud-sample/project/Build.scala). 

I'm closing this one, if you have further questions you can open it or ask me via email.

**Comment by hakandilek** [comment]
BTW, I haven't been actively contributing to this project, because it is quite stable and I am kind of "out-of-new-ideas" about it at the moment. But I am open to new ideas and contribution :)
