### ISSUE TITLE
Extension for Twixt

### ISSUE THREAD

**Issue by ianrae** [hakandilek/play2-crud#52]
Hi. I have been building an extension to play-crud called Twixt. https://github.com/ianrae/twixt

I would like to do a pull request to make some classes such as FieldMetadata more extensible.  Would that be acceptable to you?

**Comment by hakandilek** [comment]
Hi @ianrae, Twixt looks like a neat idea. Please feel free to make any kind of contributions. I'd better prefer to discuss changes based on the pull requests. As one wise hacker once said: "show me the code". :)

How are you planning to integrate play2-crud with Twixt?

**Comment by ianrae** [comment]
OK I will make a pull request.  Not expecting a lot of changes, just a few small things to make it extensible.

Twixt forms can be used on their own, but the project will include play-crud as a dependency because the automatic CRUD features are just too useful.  Integration is deriving a controller class from CRUDController, and another from DynamicCRUDController.

**Comment by hakandilek** [comment]
Ok, it sounds nice. 

I'm closing this issue and looking forward to see your pull request when you're ready.
